import { defineQuery } from "next-sanity";

import { client } from "./client";
import type { ALL_PROJECTS_QUERY_RESULT } from "./types.gen";

// A single project as returned by getAllProjects() — the shared shape the
// project components receive as props.
export type Project = ALL_PROJECTS_QUERY_RESULT[number];

// GROQ queries and the typed fetch helpers that wrap them. Result types are
// generated by `npm run typegen` into types.gen.ts and applied automatically
// to `client.fetch` via the queries defined with `defineQuery`.
//
// List queries hide future-dated documents (publishedAt > now). The by-slug
// queries do not filter on date, so a direct URL still resolves a document
// scheduled for the future — useful for previewing before it goes live.

const projectFields = `
  _id,
  _type,
  _createdAt,
  _updatedAt,
  title,
  "slug": slug.current,
  cover,
  slides[]{
    // Polymorphic media (COS-222): image or Mux video. The image branch
    // coalesces a legacy top-level \`image\` (pre-migration slides) into
    // \`media.image\`, so slides render identically whether or not the
    // \`image\`→\`media.image\` migration has run yet. Video derefs the Mux
    // asset for the playbackId the players need (T12/T13).
    "media": {
      "image": coalesce(media.image, image),
      "video": media.video{ asset->{ playbackId, assetId, status } }
    },
    variant,
    caption
  },
  order,
  summary,
  overview {
    title,
    subtitle,
    meta[]{ label, value },
    body
  },
  metadata,
  publishedAt
`;

export const ALL_PROJECTS_QUERY = defineQuery(`
  *[_type == "project" && defined(publishedAt) && publishedAt <= now()]
    | order(order asc) {${projectFields}}
`);

export const PROJECT_BY_SLUG_QUERY = defineQuery(`
  *[_type == "project" && slug.current == $slug][0] {${projectFields}}
`);

export const ALL_ARTICLES_QUERY = defineQuery(`
  *[_type == "article" && defined(publishedAt) && publishedAt <= now()]
    | order(coalesce(order, 9999) asc, publishedAt desc) {
      _id,
      _type,
      title,
      "slug": slug.current,
      lede,
      publishedAt,
      featured
    }
`);

export const ARTICLE_BY_SLUG_QUERY = defineQuery(`
  *[_type == "article" && slug.current == $slug][0] {
    _id,
    _type,
    title,
    "slug": slug.current,
    lede,
    body,
    publishedAt,
    featured,
    order
  }
`);

export const ABOUT_PAGE_QUERY = defineQuery(`
  *[_type == "aboutPage"][0] {
    _id,
    _type,
    bio,
    experienceItems,
    advisoryItems
  }
`);

export const CONTACT_PAGE_QUERY = defineQuery(`
  *[_type == "contactPage"][0] {
    _id,
    _type,
    letsTalkHeading,
    letsTalkDescription,
    email,
    instagramUrl,
    linkedinUrl,
    subjectOptions
  }
`);

export const SITE_SETTINGS_QUERY = defineQuery(`
  *[_type == "siteSettings"][0] {
    _id,
    _type,
    taglineDefault,
    metaDescription,
    ogImage,
    icon {
      ...,
      asset->{ _id, url, mimeType, extension }
    }
  }
`);

// Tag-based caching. Each fetch is tagged with the Sanity `_type` of the
// document(s) it returns, so the /api/revalidate webhook can invalidate just
// the affected content on publish. The 24h `revalidate` is a safety net for
// the case where the webhook fails to fire — content won't go stale longer
// than a day even without it.
const cacheFor = (tag: string) => ({ next: { tags: [tag], revalidate: 86400 } });

export function getAllProjects() {
  return client.fetch(ALL_PROJECTS_QUERY, {}, cacheFor("project"));
}

export function getProjectBySlug(slug: string) {
  return client.fetch(PROJECT_BY_SLUG_QUERY, { slug }, cacheFor("project"));
}

export function getAllArticles() {
  return client.fetch(ALL_ARTICLES_QUERY, {}, cacheFor("article"));
}

export function getArticleBySlug(slug: string) {
  return client.fetch(ARTICLE_BY_SLUG_QUERY, { slug }, cacheFor("article"));
}

export function getAboutPage() {
  return client.fetch(ABOUT_PAGE_QUERY, {}, cacheFor("aboutPage"));
}

export function getContactPage() {
  return client.fetch(CONTACT_PAGE_QUERY, {}, cacheFor("contactPage"));
}

export function getSiteSettings() {
  return client.fetch(SITE_SETTINGS_QUERY, {}, cacheFor("siteSettings"));
}
