import { defineQuery } from "next-sanity";

import { client } from "./client";

// GROQ queries and the typed fetch helpers that wrap them. Result types are
// generated by `npm run typegen` into types.gen.ts and applied automatically
// to `client.fetch` via the queries defined with `defineQuery`.
//
// List queries hide future-dated documents (publishedAt > now). The by-slug
// queries do not filter on date, so a direct URL still resolves a document
// scheduled for the future — useful for previewing before it goes live.

const projectFields = `
  _id,
  _type,
  _createdAt,
  _updatedAt,
  title,
  "slug": slug.current,
  cover,
  slides[]{ image, variant, caption },
  order,
  summary,
  metadata,
  publishedAt
`;

export const ALL_PROJECTS_QUERY = defineQuery(`
  *[_type == "project" && defined(publishedAt) && publishedAt <= now()]
    | order(order asc) {${projectFields}}
`);

export const PROJECT_BY_SLUG_QUERY = defineQuery(`
  *[_type == "project" && slug.current == $slug][0] {${projectFields}}
`);

export const ALL_ARTICLES_QUERY = defineQuery(`
  *[_type == "article" && defined(publishedAt) && publishedAt <= now()]
    | order(coalesce(order, 9999) asc, publishedAt desc) {
      _id,
      _type,
      title,
      "slug": slug.current,
      lede,
      publishedAt,
      featured
    }
`);

export const ARTICLE_BY_SLUG_QUERY = defineQuery(`
  *[_type == "article" && slug.current == $slug][0] {
    _id,
    _type,
    title,
    "slug": slug.current,
    lede,
    body,
    publishedAt,
    featured,
    order
  }
`);

export const ABOUT_PAGE_QUERY = defineQuery(`
  *[_type == "aboutPage"][0] {
    _id,
    _type,
    bio,
    experienceItems,
    advisoryItems
  }
`);

export const CONTACT_PAGE_QUERY = defineQuery(`
  *[_type == "contactPage"][0] {
    _id,
    _type,
    letsTalkHeading,
    letsTalkDescription,
    email,
    instagramUrl,
    linkedinUrl,
    subjectOptions
  }
`);

export const CV_QUERY = defineQuery(`
  *[_type == "cv"][0] {
    _id,
    _type,
    pdfFile,
    heading,
    intro
  }
`);

export const SITE_SETTINGS_QUERY = defineQuery(`
  *[_type == "siteSettings"][0] {
    _id,
    _type,
    taglineDefault,
    metaDescription,
    ogImage
  }
`);

export function getAllProjects() {
  return client.fetch(ALL_PROJECTS_QUERY);
}

export function getProjectBySlug(slug: string) {
  return client.fetch(PROJECT_BY_SLUG_QUERY, { slug });
}

export function getAllArticles() {
  return client.fetch(ALL_ARTICLES_QUERY);
}

export function getArticleBySlug(slug: string) {
  return client.fetch(ARTICLE_BY_SLUG_QUERY, { slug });
}

export function getAboutPage() {
  return client.fetch(ABOUT_PAGE_QUERY);
}

export function getContactPage() {
  return client.fetch(CONTACT_PAGE_QUERY);
}

export function getCv() {
  return client.fetch(CV_QUERY);
}

export function getSiteSettings() {
  return client.fetch(SITE_SETTINGS_QUERY);
}
