/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SubjectOption = {
  _type: "subjectOption";
  label?: string;
  value?: string;
};

export type ExperienceItem = {
  _type: "experienceItem";
  roleTitle?: string;
  dates?: string;
  description?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Slide = {
  _type: "slide";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  variant?: "full" | "fit";
  caption?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  taglineDefault?: string;
  metaDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  icon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  letsTalkHeading?: string;
  letsTalkDescription?: string;
  email?: string;
  instagramUrl?: string;
  linkedinUrl?: string;
  subjectOptions?: Array<
    {
      _key: string;
    } & SubjectOption
  >;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  experienceItems?: Array<
    {
      _key: string;
    } & ExperienceItem
  >;
  advisoryItems?: Array<
    {
      _key: string;
    } & ExperienceItem
  >;
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  lede?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  publishedAt?: string;
  order?: number;
  featured?: boolean;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  cover?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  slides?: Array<
    {
      _key: string;
    } & Slide
  >;
  order?: number;
  summary?: string;
  overview?: {
    title?: string;
    subtitle?: string;
    meta?: Array<{
      label?: string;
      value?: string;
      _type: "metaItem";
      _key: string;
    }>;
    body?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: null;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  };
  metadata?: {
    stage?: string;
    duration?: string;
    teamSize?: string;
    role?: string;
  };
  publishedAt?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SubjectOption
  | ExperienceItem
  | SanityImageAssetReference
  | Slide
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | ContactPage
  | AboutPage
  | Article
  | Slug
  | Project
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries.ts
// Variable: ALL_PROJECTS_QUERY
// Query: *[_type == "project" && defined(publishedAt) && publishedAt <= now()]    | order(order asc) {  _id,  _type,  _createdAt,  _updatedAt,  title,  "slug": slug.current,  cover,  slides[]{ image, variant, caption },  order,  summary,  overview {    title,    subtitle,    meta[]{ label, value },    body  },  metadata,  publishedAt}
export type ALL_PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  cover: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  slides: Array<{
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    variant: "fit" | "full" | null;
    caption: string | null;
  }> | null;
  order: number | null;
  summary: string | null;
  overview: {
    title: string | null;
    subtitle: string | null;
    meta: Array<{
      label: string | null;
      value: string | null;
    }> | null;
    body: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: null;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  } | null;
  metadata: {
    stage?: string;
    duration?: string;
    teamSize?: string;
    role?: string;
  } | null;
  publishedAt: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: PROJECT_BY_SLUG_QUERY
// Query: *[_type == "project" && slug.current == $slug][0] {  _id,  _type,  _createdAt,  _updatedAt,  title,  "slug": slug.current,  cover,  slides[]{ image, variant, caption },  order,  summary,  overview {    title,    subtitle,    meta[]{ label, value },    body  },  metadata,  publishedAt}
export type PROJECT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  cover: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  slides: Array<{
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    variant: "fit" | "full" | null;
    caption: string | null;
  }> | null;
  order: number | null;
  summary: string | null;
  overview: {
    title: string | null;
    subtitle: string | null;
    meta: Array<{
      label: string | null;
      value: string | null;
    }> | null;
    body: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: null;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  } | null;
  metadata: {
    stage?: string;
    duration?: string;
    teamSize?: string;
    role?: string;
  } | null;
  publishedAt: string | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: ALL_ARTICLES_QUERY
// Query: *[_type == "article" && defined(publishedAt) && publishedAt <= now()]    | order(coalesce(order, 9999) asc, publishedAt desc) {      _id,      _type,      title,      "slug": slug.current,      lede,      publishedAt,      featured    }
export type ALL_ARTICLES_QUERY_RESULT = Array<{
  _id: string;
  _type: "article";
  title: string | null;
  slug: string | null;
  lede: string | null;
  publishedAt: string | null;
  featured: boolean | null;
}>;

// Source: src/sanity/queries.ts
// Variable: ARTICLE_BY_SLUG_QUERY
// Query: *[_type == "article" && slug.current == $slug][0] {    _id,    _type,    title,    "slug": slug.current,    lede,    body,    publishedAt,    featured,    order  }
export type ARTICLE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _type: "article";
  title: string | null;
  slug: string | null;
  lede: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h2" | "h3" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  publishedAt: string | null;
  featured: boolean | null;
  order: number | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: ABOUT_PAGE_QUERY
// Query: *[_type == "aboutPage"][0] {    _id,    _type,    bio,    experienceItems,    advisoryItems  }
export type ABOUT_PAGE_QUERY_RESULT = {
  _id: string;
  _type: "aboutPage";
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  experienceItems: Array<
    {
      _key: string;
    } & ExperienceItem
  > | null;
  advisoryItems: Array<
    {
      _key: string;
    } & ExperienceItem
  > | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: CONTACT_PAGE_QUERY
// Query: *[_type == "contactPage"][0] {    _id,    _type,    letsTalkHeading,    letsTalkDescription,    email,    instagramUrl,    linkedinUrl,    subjectOptions  }
export type CONTACT_PAGE_QUERY_RESULT = {
  _id: string;
  _type: "contactPage";
  letsTalkHeading: string | null;
  letsTalkDescription: string | null;
  email: string | null;
  instagramUrl: string | null;
  linkedinUrl: string | null;
  subjectOptions: Array<
    {
      _key: string;
    } & SubjectOption
  > | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0] {    _id,    _type,    taglineDefault,    metaDescription,    ogImage,    icon {      ...,      asset->{ _id, url, mimeType, extension }    }  }
export type SITE_SETTINGS_QUERY_RESULT = {
  _id: string;
  _type: "siteSettings";
  taglineDefault: string | null;
  metaDescription: string | null;
  ogImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  icon: {
    asset: {
      _id: string;
      url: string | null;
      mimeType: string | null;
      extension: string | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "project" && defined(publishedAt) && publishedAt <= now()]\n    | order(order asc) {\n  _id,\n  _type,\n  _createdAt,\n  _updatedAt,\n  title,\n  "slug": slug.current,\n  cover,\n  slides[]{ image, variant, caption },\n  order,\n  summary,\n  overview {\n    title,\n    subtitle,\n    meta[]{ label, value },\n    body\n  },\n  metadata,\n  publishedAt\n}\n': ALL_PROJECTS_QUERY_RESULT;
    '\n  *[_type == "project" && slug.current == $slug][0] {\n  _id,\n  _type,\n  _createdAt,\n  _updatedAt,\n  title,\n  "slug": slug.current,\n  cover,\n  slides[]{ image, variant, caption },\n  order,\n  summary,\n  overview {\n    title,\n    subtitle,\n    meta[]{ label, value },\n    body\n  },\n  metadata,\n  publishedAt\n}\n': PROJECT_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "article" && defined(publishedAt) && publishedAt <= now()]\n    | order(coalesce(order, 9999) asc, publishedAt desc) {\n      _id,\n      _type,\n      title,\n      "slug": slug.current,\n      lede,\n      publishedAt,\n      featured\n    }\n': ALL_ARTICLES_QUERY_RESULT;
    '\n  *[_type == "article" && slug.current == $slug][0] {\n    _id,\n    _type,\n    title,\n    "slug": slug.current,\n    lede,\n    body,\n    publishedAt,\n    featured,\n    order\n  }\n': ARTICLE_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "aboutPage"][0] {\n    _id,\n    _type,\n    bio,\n    experienceItems,\n    advisoryItems\n  }\n': ABOUT_PAGE_QUERY_RESULT;
    '\n  *[_type == "contactPage"][0] {\n    _id,\n    _type,\n    letsTalkHeading,\n    letsTalkDescription,\n    email,\n    instagramUrl,\n    linkedinUrl,\n    subjectOptions\n  }\n': CONTACT_PAGE_QUERY_RESULT;
    '\n  *[_type == "siteSettings"][0] {\n    _id,\n    _type,\n    taglineDefault,\n    metaDescription,\n    ogImage,\n    icon {\n      ...,\n      asset->{ _id, url, mimeType, extension }\n    }\n  }\n': SITE_SETTINGS_QUERY_RESULT;
  }
}
